### ISSUE TITLE
Many fixes

### ISSUE THREAD

**Issue by remittor** [muink/luci-app-tn-netports#1]
https://github.com/openwrt-xiaomi/luci-app-tn-netports/commits/master/

**Comment by muink** [comment]
Merged

**Comment by remittor** [comment]
The presence of at least one port in the config will disable auto-generation of the config.
It is advisable to remove these lines:
https://github.com/muink/luci-app-tn-netports/blob/1ffa72b76a7e9a64de83f58df4e49d75ca508541/root/etc/config/luci_netports#L7-L9

**Comment by remittor** [comment]
And this file must also be deleted, since it is no longer needed. And it creates unnecessary ports.
https://github.com/muink/luci-app-tn-netports/blob/master/root/etc/uci-defaults/luci-app-tn-netports

**Comment by muink** [comment]
I've overridden the configure auto-generate feature.
I don't think this feature should be executed at runtime.

**Comment by remittor** [comment]
> I don't think this feature should be executed at runtime.

I thought so too. But I still decided to create a conf file directly when the user using LuCI page.
I tested this method. It works great!

> I've overridden the configure auto-generate feature.

Your method adds low-level variations of interfaces to the list of ports. And you need to build this list based on the `board.json` file. This is recommended to be done after implementing DSA.

**Comment by muink** [comment]
I may need to use a router to test this.  Because my current hardware does not include a switch.
Secondly, if it must be generated at runtime, I think it would be better to use [button](https://github.com/muink/luci-app-tn-netports/commit/854fda7cbd2cae449aceee24a1218ba97f22f25a).

**Comment by muink** [comment]
Patched https://github.com/muink/luci-app-tn-netports/commit/8c4f9515b32430db3fd60c6f5f294722a71cf3c6

**Comment by fildunsky** [comment]
Hi, I would love to use your app on Xiaomi AX3000T OpenWRT 23.05.4 stable release. Somehow it works only on the latest snapshots. There is a bug - any settings if I do, they are not showing any ports in Overview.

![Screenshot from 2024-09-14 22-20-34](https://github.com/user-attachments/assets/5e6345ac-8608-4c44-a998-429bc6703f63)
